version: '3.9'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_OM_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - TODO_BOT_TELEGRAM_BOT_TOKEN=${TODO_BOT_TELEGRAM_BOT_TOKEN}
  redis:
    image: redislabs/redismod:latest
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis/redis_data:/data
      - ./redis/redis.conf:/data/redis-server
